### PR TITLE
Support multi-byte characters in erlcloud_http:url_encode/1

### PR DESCRIPTION
**Pull request by jasonwebster**
Fixes https://github.com/gleber/erlcloud/issues/185

I went the path of least resistance on this one by augmenting the current system. I think the ideal solution would be to replace this completely with something that operates on binaries instead of lists, similar to what hackney does https://github.com/benoitc/hackney/blob/ae65c297dab8bbfba886b80c8d04a3593ca022bf/src/hackney_lib/hackney_url.erl#L264.

### CODE REVIEW

**Comment by ransomr** [comment]
Thank you. Is there a reason this doesn't implement support for all character ranges (4 byte UTF-8 codes)? Would be preferable to crash on those instead of encoding them incorrectly. Please also document that this is doing a UTF-8 encoding, preferably by using a `utf8_encode` method, or at least with a comment. Thank you for adding a unit test. Have you tested against AWS and verified it behaves as expected?

**Comment by jasonwebster** [comment]
Thanks for the feedback. I'm going to refactor and clean it up a bit, push some new commits, and you can take another look shortly.

**Comment by jasonwebster** [comment]
Alright, updated. Let me know if how you feel about that and I'll squash the commits before you merge.

**Comment by jasonwebster** [comment]
Going to make a couple more changes first.

**Comment by jasonwebster** [comment]
Should be all done.

I haven't tested other AWS APIs, but I can confirm that in the case of SNS this works correctly, and AWS does handle the UTF-8 encoding.

**Comment by ransomr** [comment]
Thank you.

**Pull request merged**
